services:
  postgres:
    image: postgres:17
    container_name: patient-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin_user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: default-db
    volumes:
      - C:/Users/rahul/IdeaProjects/patient-lens-ai/infrastructure/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin_user -d default-db"]
      interval: 5s
      timeout: 5s
      retries: 5

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: patient-zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: patient-kafka
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  auth-service:
    build:
      context: C:/Users/rahul/IdeaProjects/patient-lens-ai/auth-service
      dockerfile: Dockerfile
    container_name: auth-service
    ports:
      - "4005:4005"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/auth-service-db
      SPRING_DATASOURCE_USERNAME: admin_user
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_SQL_INIT_MODE: always

  billing-service:
    build:
      context: C:/Users/rahul/IdeaProjects/patient-lens-ai/billing-service
      dockerfile: Dockerfile
    container_name: billing-service
    ports:
      - "4001:4001"
      - "9001:9001"
    depends_on:
      - kafka
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092

  doctor-service:
    build:
      context: C:/Users/rahul/IdeaProjects/patient-lens-ai/doctor-service
      dockerfile: Dockerfile
    container_name: doctor-service
    ports:
      - "4003:4003"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/doctor-service-db
      SPRING_DATASOURCE_USERNAME: admin_user
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_SQL_INIT_MODE: always


  patient-service:
    build:
      context: C:/Users/rahul/IdeaProjects/patient-lens-ai/patient-service
      dockerfile: Dockerfile
    container_name: patient-service
    ports:
      - "4000:4000"
    depends_on:
      postgres:
        condition: service_healthy
      kafka:
        condition: service_started
      billing-service:
        condition: service_started
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/patient-service-db
      SPRING_DATASOURCE_USERNAME: admin_user
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_SQL_INIT_MODE: always
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      BILLING_SERVICE_ADDRESS: billing-service
      BILLING_SERVICE_GRPC_PORT: 9001

  api-gateway:
    build:
      context: C:/Users/rahul/IdeaProjects/patient-lens-ai/api-gateway
      dockerfile: Dockerfile
    container_name: api-gateway
    ports:
      - "4004:4004"
    depends_on:
      - auth-service
      - patient-service
      - billing-service
      - doctor-service
      - appointment-service
    environment:
      AUTH_SERVICE_URL: http://auth-service:4005

  appointment-service:
    build:
      context: C:/Users/rahul/IdeaProjects/patient-lens-ai/appointment-service
      dockerfile: Dockerfile
    container_name: appointment-service
    ports:
      - "4002:4002"
    depends_on:
      postgres:
        condition: service_healthy
      kafka:
        condition: service_started
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/appointment-service-db
      SPRING_DATASOURCE_USERNAME: admin_user
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_SQL_INIT_MODE: always
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092

  payment-service:
    build:
      context: C:/Users/rahul/IdeaProjects/patient-lens-ai/payment-service
      dockerfile: Dockerfile
    container_name: payment-service
    ports:
      - "4006:4006"
      - "9006:9006"
    depends_on:
      postgres:
        condition: service_healthy
      kafka:
        condition: service_started
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/payment-service-db
      SPRING_DATASOURCE_USERNAME: admin_user
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_SQL_INIT_MODE: always
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092

  notification-service:
    build:
      context: C:/Users/rahul/IdeaProjects/patient-lens-ai/notification-service
      dockerfile: Dockerfile
    container_name: notification-service
    ports:
      - "4008:4008"
      - "9008:9008"
    depends_on:
      postgres:
        condition: service_healthy
      kafka:
        condition: service_started
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/notification-service-db
      SPRING_DATASOURCE_USERNAME: admin_user
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_SQL_INIT_MODE: always
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092

