server:
  port: 4004
auth:
  service:
    url: ${AUTH_SERVICE_URL:http://localhost:4005}
spring:
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:5173,https://patient-lens-ai.onrender.com"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true
      server:
        webflux:
          routes:
            - id: patient-service-route
              uri: http://patient-service:4000
              predicates:
                - Path=/api/patients/**
              filters:
                - StripPrefix=1
                - JwtValidation
            - id: api-docs-patient-route
              uri: http://patient-service:4000
              predicates:
                  - Path=/api-docs/patients
              filters:
                - RewritePath=/api-docs/patients,/v3/api-docs
            - id: auth-service-route
              uri: http://auth-service:4005
              predicates:
                - Path=/auth/**
              filters:
                - StripPrefix=1
            - id: api-docs-auth-route
              uri: http://auth-service:4005
              predicates:
                  - Path=/api-docs/auth
              filters:
                - RewritePath=/api-docs/auth,/v3/api-docs
            - id: doctor-service-route
              uri: http://doctor-service:4003
              predicates:
                - Path=/api/doctors/**
              filters:
                - StripPrefix=1
                - JwtValidation
            - id: appointment-service-route
              uri: http://appointment-service:4002
              predicates:
                - Path=/api/appointments/**
              filters:
                - StripPrefix=1
                - JwtValidation
            - id: billing-service-route
              uri: http://billing-service:4001
              predicates:
                - Path=/api/billing/**
              filters:
                - StripPrefix=1
                - JwtValidation
            - id: ai-service-route
              uri: http://ai-service:4010
              predicates:
                - Path=/api/ai/**
              filters:
                - StripPrefix=1
                - JwtValidation
            - id: analytics-service-route
              uri: http://analytics-service:4009
              predicates:
                - Path=/api/analytics/**
              filters:
                - StripPrefix=1
                - JwtValidation