spring.application.name=payment-service
server.port=4006
grpc.server.port=9006

spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.ByteArraySerializer

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
